# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "ğŸ¥ English"
languagedirection = "ltr"
title = "01MI"
weight = 1

[fr]
languageName = "ğŸ¥ FranÃ§ais"
languagedirection = "ltr"
title = "01MI"
weight = 2
